model_list:

  # =========================
  # Agent Pool
  # =========================

  - model_name: agent-pool
    litellm_params:
      model: groq/openai/gpt-oss-20b
      api_key: os.environ/GROQ_API_KEY_agent1
      rpm: 30

  - model_name: agent-pool
    litellm_params:
      model: openrouter/liquid/lfm-2.5-2.6b:free
      api_key: os.environ/OPENROUTE_API_agent2
      rpm: 30


  # =========================
  # Embedding
  # =========================

  - model_name: embedding-pool
    litellm_params:
      model: openrouter/voyageai/voyage-code-4
      api_key: os.environ/OPENROUTE_API_emb1
      rpm: 100

# =========================
# LiteLLM Settings
# =========================

litellm_settings:
  cache: true

  cache_params:
    type: local

  drop_params: true


# =========================
# Router Settings
# =========================

router_settings:
  routing_strategy: usage-based-routing-v2
  num_retries: 2
  allowed_fails: 1
  cooldown_time: 60